### ISSUE TITLE
REPORTE DE PRACTICA 6 PROCESO DE MEJORA DE MODELO DE NEGOCIO

### ISSUE THREAD

**Issue by IrvinSanchez-dev** [SistemasTecTlaxiaco/actividad-5-proceso-de-negocio-en-bizagi-con-web-30-mejorado-dinamita#1]
[PRACTICA 6 PROCESO DE MEJORA DE NEGOCIO.pdf](https://github.com/user-attachments/files/17122151/PRACTICA.6.PROCESO.DE.MEJORA.DE.NEGOCIO.pdf)
EQUIPO:
Diego Cruz Cruz
Marco Uriel Rosas Garcia
Irvin Jimenez Sanchez

**Comment by Kevinosorio77** [comment]
Trabajo revisado  cumple con la rubrica porcentaje de 20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
